# Need these for a more recent CMake on Linux
sudo: required
dist: trusty

os:
  - linux

language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt487-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++ gcc-multilib g++-multilib qt4-qmake libqt4-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

after_script:
  - test
#cmake --build . --target test

